using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SurveyBot.Core.Models.Domain
{
    /// <summary>
    /// результаты прохождения опроса
    /// </summary>
    public class SurveyResult
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int Id { get; set; }
        public ObjectId SurveyId { get; set; }
        public ObjectId ExecutorId { get; set; }
        public string ExecutorName { get; set; }
        public IEnumerable<SurveyAnswer> Answers { get; set; }
    }
}