using System.Collections.Generic;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;

namespace SurveyBot.Core.Models.Domain
{
    /// <summary>
    /// результаты прохождения опроса
    /// </summary>
    public class SurveyResult
    {
        [BsonId(IdGenerator = typeof(StringObjectIdGenerator))]
        // standard BSonId generated by MongoDb
        public string Id { get; set; }

        public ObjectId SurveyId { get; set; }
        public ObjectId ExecutorId { get; set; }
        public string ExecutorName { get; set; }
        public IEnumerable<SurveyAnswer> Answers { get; set; }
    }
}