using System;
using System.Collections.Generic;
using System.Text;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SurveyBot.Core.Models.Domain
{
    /// <summary>
    /// шаблон опроса
    /// </summary>
    public class Survey
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int Id { get; set; }
        public int CreatorId { get; set; } = 0;
        public DateTime UpdateDate { get; set; } = DateTime.Now;
        public DateTime CreateDate { get; set; } = DateTime.Now;
        public IEnumerable<SurveyQuestion> Questions { get; set; }
    }
}
