using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SurveyBot.Core.Models.Domain
{
    /// <summary>
    /// шаблон вопроса
    /// </summary>
    public class SurveyQuestion
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public int Id { get; set; }
        public int QuestionType { get; set; }
        public string Text { get; set; }
        public int Index { get; set; }
    }
}