using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SurveyBot.Core.Models.Domain
{
    /// <summary>
    /// ответ на вопрос опроса
    /// </summary>
    public class SurveyAnswer
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        public ObjectId SurveyQuestionId { get; set; }
        public string Answer { get; set; }
    }
}